name: Release and Publish

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para fazer push de commits e tags
      issues: write # Permissão para comentar em issues (opcional, mas recomendado)
      pull-requests: write # Permissão para comentar em PRs (opcional, mas recomendado)
      id-token: write # ERMISSÃO OBRIGATÓRIA PARA O OIDC DO NPM

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          # não usa mais o registry como ta usando o oidc do npm registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test # Opcional, mas altamente recomendado

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true # Habilita a geração de arquivos de proveniência para o npm
        run: npx semantic-release